/*
 * Copyright (c) 2026 Nathan Keynes <nkeynes@deadcoderemoval.net>
 *
 * This file is part of Fabr.
 *
 * Fabr is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * Fabr is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * Fabr. If not, see <https://www.gnu.org/licenses/>.
 */

/* Note: this file is run by `fabr test`, not by the workspace jest setup
 * (it is excluded there). It uses the describe/it GLOBALS rather than importing
 * them, so it runs under whichever runner the target selects — importing from
 * "node:test" would make it invisible to a jest-framework runner. */

import * as assert from "node:assert/strict";
import type { ITestResult } from "@fabr-build/core";
import { buildReport, describeSnapshotFailure, formatTestFailures, formatTestSummary } from "./Report";

function test(name: string, status: ITestResult["status"], extra?: Partial<ITestResult>): ITestResult {
  return { name, status, duration: 0, ...extra };
}

describe("buildReport", () => {
  it("summarizes by status", () => {
    const report = buildReport(
      [test("a", "passed"), test("b", "failed"), test("c", "passed"), test("d", "skipped"), test("e", "pending")],
      100,
      250
    );
    assert.deepEqual(report.results.summary, {
      tests: 5,
      passed: 2,
      failed: 1,
      pending: 1,
      skipped: 1,
      other: 0,
      start: 100,
      stop: 250,
    });
    assert.equal(report.results.tool.name, "fabr");
  });

  it("summarizes an empty run", () => {
    assert.deepEqual(buildReport([], 5, 7).results.summary, {
      tests: 0,
      passed: 0,
      failed: 0,
      pending: 0,
      skipped: 0,
      other: 0,
      start: 5,
      stop: 7,
    });
  });
});

describe("formatTestSummary", () => {
  it("reports an all-green run", () => {
    assert.equal(formatTestSummary(buildReport([test("a", "passed"), test("b", "passed")], 0, 0)), "2 tests passed");
  });

  it("mentions skipped tests", () => {
    assert.equal(
      formatTestSummary(buildReport([test("a", "passed"), test("b", "skipped")], 0, 0)),
      "1 test passed (1 skipped)"
    );
  });

  it("reports failures", () => {
    assert.equal(formatTestSummary(buildReport([test("a", "failed"), test("b", "passed")], 0, 0)), "1 of 2 tests failed");
  });
});

describe("formatTestFailures", () => {
  it("lists each failed test with its location and first message line", () => {
    const text = formatTestFailures(
      buildReport(
        [
          test("works", "passed"),
          test("breaks", "failed", { filePath: "core/Thing.test.js", message: "expected 1 to equal 2\nlong stack" }),
          test("also breaks", "failed"),
        ],
        0,
        0
      )
    );
    assert.deepEqual(text.split("\n"), [
      "2 of 3 tests failed",
      "  breaks (core/Thing.test.js): expected 1 to equal 2",
      "  also breaks",
    ]);
  });
});

describe("describeSnapshotFailure", () => {
  /** An error as node:test's snapshot assertion raises it — recognized by the
   * frame it was thrown from. */
  function snapshotError(fields: object, message = "Expected values to be strictly equal"): Error {
    const error = Object.assign(new Error(message), fields);
    error.stack = `${message}\n    at TestContext.snapshotAssertion (node:internal/test_runner/snapshot:207:9)\n    at it (/work/a.test.js:2:5)`;
    return error;
  }

  it("leaves any other failure alone", () => {
    assert.equal(describeSnapshotFailure(new Error("Missing snapshots can be generated somehow.")), undefined);
  });

  it("renders a mismatch as a line diff, with fabr's remedy", () => {
    const failure = describeSnapshotFailure(snapshotError({ expected: '\n{\n  "a": 1,\n  "b": 2\n}\n', actual: '\n{\n  "a": 1,\n  "b": 3\n}\n' }));
    assert.match(failure?.message ?? "", /does not match its recorded snapshot.*'fabr test -u'/);
    assert.equal(failure?.trace, ['- recorded', '+ actual', '', '  {', '    "a": 1,', '-   "b": 2', '+   "b": 3', '  }'].join("\n"));
  });

  it("diffs lines added and removed around common ones", () => {
    const failure = describeSnapshotFailure(snapshotError({ expected: "a\nb\nc", actual: "b\nc\nd" }));
    assert.equal(failure?.trace, ["- recorded", "+ actual", "", "- a", "  b", "  c", "+ d"].join("\n"));
  });

  it("names fabr's flag, not node's, for a test with no record", () => {
    const noFile = snapshotError(
      { code: "ERR_INVALID_STATE", cause: { code: "ENOENT" } },
      "Invalid state: Cannot read snapshot file '/work/__snapshots__/a.test.ts.snap.' Missing snapshots can be generated by rerunning the command with the --test-update-snapshots flag."
    );
    const noEntry = snapshotError(
      { code: "ERR_INVALID_STATE" },
      "Invalid state: Snapshot 'suite > case 4' not found in '/work/__snapshots__/a.test.ts.snap.' Missing snapshots can be generated by rerunning the command with the --test-update-snapshots flag."
    );
    for (const error of [noFile, noEntry]) {
      assert.deepEqual(describeSnapshotFailure(error), { message: "This test has no recorded snapshot. Run 'fabr test -u' to record one." });
    }
  });

  it("keeps node's reason for an unreadable record, minus its flag", () => {
    const failure = describeSnapshotFailure(
      snapshotError(
        { code: "ERR_INVALID_STATE", cause: { code: "EACCES" } },
        "Invalid state: Cannot read snapshot file '/work/a.snap.' Missing snapshots can be generated by rerunning the command with the --test-update-snapshots flag."
      )
    );
    assert.equal(failure?.message, "Invalid state: Cannot read snapshot file '/work/a.snap.' Run 'fabr test -u' to record them again.");
  });
});
